name: Build image and deploy to Caprover

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Declare git variables
        id: git_vars
        shell: bash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_IMAGE }}:${{ steps.git_vars.outputs.sha_short }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: Caprover Deploy
        uses: stardustventures/caprover-deploy@v2
        with:
          # CapRover admin panel URL. Ex. https://captain.root.domain.com
          server: ${{ secrets.CAPROVER_URL }}
          # CapRover admin password. Use $\{{ secrets.CAPROVER_PASSWORD }} for better security.
          password: ${{ secrets.CAPROVER_PASSWORD }}
          # Application name on the CapRover server. Must exists.
          appname: ${{ secrets.CAPROVER_APP }}
          # Container image registry url
          image: ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_IMAGE }}:${{ steps.git_vars.outputs.sha_short }}
        
